# Step 1: Set up kubectl to connect to your GKE cluster
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'module-3-cluster'
    - '--region'
    - 'us-central1'  # Use region instead of zone
    - '--project'
    - 'module-3-recap'
